sudo: required

dist: trusty

language: ruby

cache:
  bundler: true

rvm:
  - 2.2.2

addons:
  postgresql: "9.3"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y postgresql-9.3-postgis-2.1 gdal-bin proj-bin libgeos-dev libgeos++-dev libproj-dev wkhtmltopdf
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -U postgres -c "create extension postgis"
  - sudo -u postgres createdb template_postgis
  - sudo -u postgres psql template_postgis -c "UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template_postgis'"
  - sudo -u postgres psql -q template_postgis < /usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql
  - sudo -u postgres psql -q template_postgis < /usr/share/postgresql/9.3/contrib/postgis-2.1/spatial_ref_sys.sql
  - curl -O https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.1.1/elasticsearch-2.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-2.1.1.deb
  - sudo /usr/share/elasticsearch/bin/plugin install analysis-kuromoji
  - sudo /usr/share/elasticsearch/bin/plugin install delete-by-query
  - sudo service elasticsearch start
  - gem install bundler
  - mkdir -p tmp/pids
  - echo -e "--format documentation\n--color\n--require spec_helper\n--profile\n--tty" > .rspec

before_script:
  - sleep 15
  - ci/scripts/before_script.sh

env:
  - TRAVIS_CI=true TESTFOLDER=spec/models
  - TRAVIS_CI=true TESTFOLDER='spec/controllers spec/helpers spec/initializers spec/lib spec/views'

script: "bundle exec rspec $TESTFOLDER"

notifications:
  slack:
    secure: a5oKH3x+irU27B+5f9hZPLEKl4gFPjj74UXPvVPKJdJ8shnDVwZkJdzsCV9u2qirD07TzZNCKGprTIG4zWJdYyMVmKucwT7hRMPCGIBu/2cGvSBfOSyiDHLNmvUvA6yOaECWT7h8CpTE2wqxNV8avqGlc20oNrxlJT2bpVTTU4U=

